"""
Emotion lexicon and modifiers.
"""

from __future__ import annotations

from dataclasses import dataclass

from .types import EmotionType


@dataclass(frozen=True)
class EmotionLexicon:
    """Lexicon and modifiers for emotion analysis."""

    keywords: dict[EmotionType, list[tuple[str, float]]]
    intensifiers: list[str]
    diminishers: list[str]
    negations: list[str]
    positive_hints: list[str]
    negative_hints: list[str]


DEFAULT_LEXICON = EmotionLexicon(
    keywords={
        EmotionType.HAPPY: [
            ("happy", 1.0),
            ("joy", 0.9),
            ("glad", 0.8),
            ("delighted", 1.0),
            ("pleased", 0.8),
            ("cheerful", 0.8),
            ("grateful", 0.7),
            ("love", 0.8),
            ("awesome", 0.9),
            ("great", 0.7),
            ("nice", 0.6),
            ("amazing", 0.8),
            ("yay", 0.7),
            (":)", 0.8),
            (":-)", 0.8),
            ("^_^", 0.7),
            (":D", 0.9),
            ("开心", 1.0),
            ("高兴", 1.0),
            ("快乐", 1.0),
            ("欢喜", 0.9),
            ("愉快", 0.8),
            ("幸福", 0.9),
            ("满足", 0.7),
            ("满意", 0.8),
            ("真好", 0.7),
            ("太好了", 0.9),
            ("棒", 0.6),
            ("好耶", 0.8),
        ],
        EmotionType.SAD: [
            ("sad", 1.0),
            ("unhappy", 0.9),
            ("depressed", 1.0),
            ("gloomy", 0.8),
            ("miserable", 1.0),
            ("down", 0.6),
            ("upset", 0.8),
            ("heartbroken", 1.0),
            ("cry", 0.7),
            ("crying", 0.8),
            ("T_T", 0.9),
            ("Q_Q", 0.9),
            ("QAQ", 0.9),
            (";_;", 0.8),
            (":'(", 0.9),
            ("难过", 1.0),
            ("伤心", 1.0),
            ("悲伤", 1.0),
            ("沮丧", 0.9),
            ("失落", 0.9),
            ("郁闷", 0.8),
            ("心碎", 1.0),
            ("想哭", 0.9),
            ("难受", 0.8),
        ],
        EmotionType.ANGRY: [
            ("angry", 1.0),
            ("furious", 1.0),
            ("mad", 0.8),
            ("annoyed", 0.8),
            ("irritated", 0.8),
            ("rage", 1.0),
            ("hate", 0.8),
            ("pissed", 0.9),
            (">:(", 1.0),
            ("D:<", 0.9),
            ("生气", 1.0),
            ("愤怒", 1.0),
            ("恼火", 0.9),
            ("气死", 1.0),
            ("火大", 0.9),
            ("烦死", 0.9),
            ("讨厌", 0.8),
            ("气炸", 1.0),
        ],
        EmotionType.SURPRISED: [
            ("surprised", 1.0),
            ("shocked", 1.0),
            ("amazed", 0.9),
            ("astonished", 1.0),
            ("wow", 0.7),
            ("omg", 0.8),
            ("wtf", 1.0),
            ("what the", 0.9),
            (":O", 0.9),
            ("O_O", 0.9),
            ("惊讶", 1.0),
            ("震惊", 1.0),
            ("吃惊", 0.9),
            ("意外", 0.8),
            ("没想到", 0.9),
            ("居然", 0.8),
            ("竟然", 0.8),
            ("天啊", 0.9),
            ("哇", 0.7),
            ("真的假的", 0.8),
        ],
        EmotionType.EXCITED: [
            ("excited", 1.0),
            ("thrilled", 1.0),
            ("eager", 0.8),
            ("pumped", 0.9),
            ("can't wait", 0.9),
            ("XD", 0.8),
            ("激动", 1.0),
            ("兴奋", 1.0),
            ("期待", 0.8),
            ("热血", 0.8),
            ("燃", 0.7),
            ("冲", 0.6),
            ("爽", 0.7),
            ("嗨", 0.6),
            ("期待已久", 0.9),
        ],
        EmotionType.CURIOUS: [
            ("curious", 1.0),
            ("interested", 0.8),
            ("wondering", 0.9),
            ("intrigued", 0.9),
            ("why", 0.7),
            ("how", 0.6),
            ("what if", 0.8),
            ("想知道", 1.0),
            ("好奇", 1.0),
            ("请问", 0.8),
            ("想问", 0.8),
            ("了解一下", 0.7),
            ("有意思", 0.6),
        ],
        EmotionType.CONFUSED: [
            ("confused", 1.0),
            ("puzzled", 0.9),
            ("perplexed", 0.9),
            ("lost", 0.8),
            ("not sure", 0.8),
            ("don't understand", 1.0),
            (":/", 0.8),
            ("不明白", 1.0),
            ("搞不懂", 1.0),
            ("迷茫", 0.9),
            ("困惑", 1.0),
            ("懵", 0.7),
            ("糊涂", 0.8),
            ("奇怪", 0.6),
            ("看不懂", 0.9),
        ],
        EmotionType.FEARFUL: [
            ("afraid", 1.0),
            ("scared", 1.0),
            ("frightened", 1.0),
            ("terrified", 1.0),
            ("anxious", 0.9),
            ("nervous", 0.8),
            ("panic", 1.0),
            ("害怕", 1.0),
            ("恐惧", 1.0),
            ("担心", 0.8),
            ("紧张", 0.8),
            ("怕", 0.7),
            ("不安", 0.8),
            ("慌", 0.8),
        ],
        EmotionType.DISGUSTED: [
            ("disgusted", 1.0),
            ("gross", 0.9),
            ("nasty", 0.8),
            ("ew", 0.9),
            ("恶心", 1.0),
            ("反胃", 0.9),
            ("厌恶", 0.9),
            ("作呕", 0.9),
            ("嫌弃", 0.7),
            ("脏", 0.6),
        ],
        EmotionType.SHY: [
            ("shy", 1.0),
            ("embarrassed", 1.0),
            ("awkward", 0.8),
            ("blush", 0.8),
            ("害羞", 1.0),
            ("不好意思", 0.9),
            ("脸红", 0.8),
            ("尴尬", 0.9),
            ("羞涩", 0.8),
        ],
        EmotionType.SLEEPY: [
            ("sleepy", 1.0),
            ("tired", 0.9),
            ("exhausted", 1.0),
            ("drowsy", 0.9),
            ("疲惫", 1.0),
            ("困", 0.8),
            ("犯困", 0.9),
            ("想睡", 1.0),
            ("打瞌睡", 0.9),
            ("哈欠", 0.7),
            ("累", 0.7),
            ("zzz", 0.8),
        ],
    },
    intensifiers=[
        "very",
        "really",
        "super",
        "extremely",
        "so",
        "too",
        "太",
        "很",
        "非常",
        "超级",
        "特别",
        "真",
        "真的",
        "巨",
        "爆",
        "贼",
    ],
    diminishers=[
        "a bit",
        "a little",
        "kind of",
        "kinda",
        "sort of",
        "稍微",
        "有点",
        "一点",
        "有些",
        "可能",
        "maybe",
    ],
    negations=[
        "not",
        "no",
        "never",
        "n't",
        "without",
        "不",
        "没",
        "没有",
        "无",
        "别",
        "难以",
        "不太",
    ],
    positive_hints=[
        "开心",
        "快乐",
        "幸福",
        "喜欢",
        "爱",
        "棒",
        "太好了",
        "great",
        "awesome",
        "love",
        "yay",
    ],
    negative_hints=[
        "难过",
        "伤心",
        "糟糕",
        "讨厌",
        "烦",
        "生气",
        "痛苦",
        "崩溃",
        "bad",
        "terrible",
        "hate",
    ],
)
